### ISSUE TITLE
Commands and stuff just won't load

### ISSUE THREAD

**Issue by MrNooberDude** [ImaDoofus/HousingEditor#11]
So... I don't know how this could've happened, but the commands just don't register, nor do the features in GUIs. Here is the list of mods Minecraft was running (forge 1.8.9)
Essential
ChatTriggers
Sk1er Old Animations
Patcher
SimpleToggleSprint
Smooth Scrolling Everywhere
Optifine

CT Modules:
ixMod
HousingEditor

I copied the folder inside the zip (from the code of the master tree) into C:\Users\[name]\AppData\Roaming\.minecraft\config\ChatTriggers\modules

Hopefully this is the right place put something like this.

**Comment by ImaDoofus** [comment]
This is a great place for issues but you may get a faster response if you use Discord.

I would begin by making sure Chattriggers is on the latest version and that HousingEditor shows in /ct modules
Next, check that the HousingEditor-master.zip is unzipped and the resulting folder is renamed to HousingEditor. With no -master after it
If that doesn't work try disabling each mod to find the problematic one, optifine in particular has caused issues for some people.
