### ISSUE TITLE
another bug and ig only for me

### ISSUE THREAD

**Issue by keyboardbored** [ImaDoofus/HousingEditor#21]
when i do /ct reload after reloading it says [21:24] Error: java.lang.NoClassDefFoundError: org/brotli/dec/State. it says same thing when i trying paste function id. Edit: it says tht i need to update to 1.2.0 but when i download housing-master (that thing that on main page) nothing works :\

**Comment by ImaDoofus** [comment]
This error is usually due to optifine or some other conflicting mod, try removing mods until you find the culprit.

**Comment by ImaDoofus** [comment]
This error is usually due to optifine or some other conflicting mod, try removing mods until you find the culprit. 🙂

**Comment by keyboardbored** [comment]
(IK IM VERY VERY LATE) helo, i dont have optifine on. Or any mods except chat triggers. Other verisons of that mod doesnt works, and when i rename housingeditor-master to housingeditor, it keep says that thing

**Comment by keyboardbored** [comment]
Ok, nevermind.. it fixed itself
